apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ include "myhelm1.fullname" . }}
  labels:
    {{- include "myhelm1.labels" . | nindent 4 }}  
spec:
  template:
    metadata: 
      name: {{ include "myhelm1.fullname" . }}
  encryptedData:
  {{- range $key, $val := .Values.encryptedData }}
    {{ $key }}: {{ $val | quote }}
  {{- end }}